---
- name: Converge
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: "Include nginx-proxy-role"
      include_role:
        name: "nginx-proxy-role"
      vars:
        graylog_fqdn: "graylog.YourDomain.pl"
        bind_ip: "127.0.0.1"
