---
- name: Converge
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: "Include ansible_roles_nginx_proxy"
      include_role:
        name: "ansible_roles_nginx_proxy"
      vars:
        graylog_fqdn: "graylog.YourDomain.pl"
        bind_ip: "127.0.0.1"
